# using conda with Azure DevOps: https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/anaconda?view=azure-devops&tabs=ubuntu-16-04
# not using strategy matrix because conda needs to be initialized differently for all operating systems

trigger:
- main

jobs:
  # - job: windows
  ## this is weird "Failed to build pickle5" coming up during dependency installation
  #   pool:
  #     vmImage: windows-latest
  #   steps:
  #     - powershell: Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
  #       displayName: Add conda to PATH
    
  #     - template: .azure-pipelines/steps.yml
  
  - job: linux
    pool:
      vmImage: ubuntu-latest
    steps:
      - bash: echo "##vso[task.prependpath]$CONDA/bin"
        displayName: Add conda to PATH
    
      - template: .azure-pipelines/steps.yml

  - job: macOS
    pool:
      vmImage: macOS-latest
    steps:
      - bash: echo "##vso[task.prependpath]$CONDA/bin"
        displayName: Add conda to PATH
        
      - bash: sudo chown -R $USER $CONDA
        displayName: Take ownership of conda installation
    
      - template: .azure-pipelines/steps.yml
